// placeIdentityCore — the PURE half of src/placeIdentity.ts (candidate pick, speech name, address
// tokens, quip validation). No imports at all, so tools/sim-qc/place_identity_test.mts can drive
// it under plain Node; the network half (Google nearby search, backend quip) stays in
// src/placeIdentity.ts, which re-exports everything here.

export type ArrivalPlace = {
  name: string;               // speech-friendly (corporate suffixes stripped)
  rawName: string;
  primaryType: string | null; // Google Places (New) primary type, e.g. "motorcycle_dealer"
  types: string[];
  openNow: boolean | null;
  summary: string | null;     // Google's editorial summary when it has one
  placeId: string | null;
  distM: number;
  /** A one-line closer generated by the backend for THIS place, when available (validated). */
  quip?: string | null;
};

export type PlaceCandidate = {
  placeId?: string | null;
  name: string;
  primaryType?: string | null;
  types?: string[] | null;
  formattedAddress?: string | null;
  lat: number;
  lng: number;
  openNow?: boolean | null;
  summary?: string | null;
};

/** Search radius: a strata unit's pin is within a few metres; 40 m still holds one building. */
export const PLACE_SEARCH_RADIUS_M = 40;
/** Without an address to match, the nearest business must be this close to count as "here". */
export const PLACE_NEAREST_MAX_M = 25;

const CORP_SUFFIX = /\s+(inc\.?|ltd\.?|llc|corp\.?|corporation|limited|co\.?|company)$/i;
// A trailing generic noun that only repeats what the place IS ("… Motorcycle Company" → the
// type already says motorcycle dealer). Dropped only when two or more words remain.
const GENERIC_TAIL = /\s+(motorcycle|motorcycles|motors|automotive|restaurant|cafe|store|shop|services|service|group)$/i;

/** "International Motorsports Motorcycle Company" → "International Motorsports". */
export function speechName(raw: string): string {
  let n = (raw || "").trim().replace(/\s+/g, " ");
  for (let i = 0; i < 3 && CORP_SUFFIX.test(n); i++) n = n.replace(CORP_SUFFIX, "").trim();
  const words = n.split(" ");
  if (words.length >= 3 && GENERIC_TAIL.test(n)) n = n.replace(GENERIC_TAIL, "").trim();
  return n;
}

function haversineM(aLat: number, aLng: number, bLat: number, bLng: number): number {
  const R = 6371000, toR = Math.PI / 180;
  const dLat = (bLat - aLat) * toR, dLng = (bLng - aLng) * toR;
  const s = Math.sin(dLat / 2) ** 2 + Math.cos(aLat * toR) * Math.cos(bLat * toR) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(s));
}

const STREET_WORD = /^(st|street|ave|avenue|rd|road|blvd|boulevard|way|dr|drive|cres|crescent|hwy|highway|pl|place|ct|court|ln|lane|terr|terrace|pkwy|parkway|trail|close|gate|row|sq|square|loop|circle|cir)\.?,?$/i;

/**
 * The civic number and (optional) unit in a typed address. BC streets are often NUMBERS
 * ("200A Street"), so the leading numeric tokens are read against what follows them:
 *   "9420 200A St"          → civic 9420, street 200A
 *   "100 9420 200A St"      → unit 100, civic 9420, street 200A
 *   "#100-9420 200A St"     → unit 100, civic 9420
 *   "9420 200A St Unit 100" → civic 9420, unit 100 (the unit named at the tail)
 *   "100 9420 Main St"      → unit 100, civic 9420
 */
export function addressTokens(label?: string | null): { civic: string | null; unit: string | null } {
  const t = (label || "").trim();
  if (!t) return { civic: null, unit: null };
  const words = t.replace(/^(#|unit\s*|suite\s*|ste\.?\s*)/i, "").replace(/[-\u2013,]/g, " ").trim().split(/\s+/);
  const nums: string[] = [];
  let i = 0;
  while (i < words.length && /^\d+[a-z]?$/i.test(words[i])) { nums.push(words[i].toLowerCase()); i++; }
  const next = words[i] || "";
  // a unit named AFTER the street ("… St Unit 200, Langley"), anywhere in the tail
  const unitTail = t.slice(t.search(/[a-z]/i) >= 0 ? 0 : 0).match(/(?:#|\bunit\s*|\bsuite\s*|\bste\.?\s*)(\d+[a-z]?)\b/i);
  const tailUnit = unitTail ? unitTail[1].toLowerCase() : null;
  if (!nums.length) return { civic: null, unit: null };
  if (STREET_WORD.test(next) && nums.length >= 2) {
    // the last number IS the street; the one before it is the civic; one more before = the unit
    const civic = nums[nums.length - 2];
    const unit = nums.length >= 3 ? nums[nums.length - 3] : tailUnit;
    return { civic, unit };
  }
  if (nums.length >= 2) return { civic: nums[1], unit: nums[0] };
  return { civic: nums[0], unit: tailUnit };
}

function addrHasCivic(addr: string, civic: string): boolean {
  return new RegExp(`(^|[^0-9a-z])${civic}(?=[^0-9a-z]|$)`, "i").test(addr);
}
function addrHasUnit(addr: string, unit: string): boolean {
  return new RegExp(`(?:#|unit\\s*|suite\\s*|ste\\.?\\s*)${unit}(?=[^0-9a-z]|$)`, "i").test(addr);
}

/**
 * Pick the ONE business the driver is arriving at, or null. With an address in the label,
 * the candidate must share its civic number (and unit, when the label has one); otherwise the
 * nearest candidate within PLACE_NEAREST_MAX_M. Address-only "places" (no primary type) never
 * count — they are the address again, not a business.
 */
export function pickArrivalPlace(
  dest: { lat: number; lng: number; label?: string | null },
  candidates: PlaceCandidate[],
): ArrivalPlace | null {
  const scored = candidates
    .filter((c) => c && typeof c.lat === "number" && typeof c.lng === "number" && c.name && c.primaryType)
    .map((c) => ({ c, d: haversineM(dest.lat, dest.lng, c.lat, c.lng) }))
    .sort((a, b) => a.d - b.d);
  if (!scored.length) return null;
  const { civic, unit } = addressTokens(dest.label);
  let hit: { c: PlaceCandidate; d: number } | undefined;
  if (civic) {
    const sameCivic = scored.filter((s) => addrHasCivic(s.c.formattedAddress || "", civic));
    if (unit) hit = sameCivic.find((s) => addrHasUnit(s.c.formattedAddress || "", unit));
    // A unit was named and nobody matches it: the driver is going to a different suite than the
    // one Google knows — say the address, not a neighbour's business.
    if (!hit && !unit && sameCivic.length >= 1) hit = sameCivic[0];
  } else if (scored[0].d <= PLACE_NEAREST_MAX_M) {
    hit = scored[0];
  }
  if (!hit) return null;
  const c = hit.c;
  return {
    name: speechName(c.name), rawName: c.name,
    primaryType: c.primaryType ?? null, types: Array.isArray(c.types) ? c.types.slice() : [],
    openNow: typeof c.openNow === "boolean" ? c.openNow : null,
    summary: c.summary ?? null, placeId: c.placeId ?? null, distM: Math.round(hit.d),
  };
}

/** A generated closer is spoken only if it is short, plain and dash/emoji free. */
export function validQuip(q: unknown): string | null {
  if (typeof q !== "string") return null;
  const t = q.trim().replace(/\s+/g, " ");
  if (!t || t.length > 90) return null;
  if (t.split(" ").length > 14) return null;
  if (/[—–\-]|[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(t)) return null;
  return t;
}

