#!/usr/bin/env python3
"""bake_hazards.py — the crew-report pins: the search-category teardrop (bake.py bake_pin, DEEP fill) with the
Report panel's Apple-symbol glyph (assets/carplay-glyphs/report/gen_b.py) in the category's BRIGHT shade on
the head. Police = EV charging, Crash = Hospital, Hazard = Fast Food, Traffic = Gas (Jeff, 2026-09-25).
Emits src/hazardPinImages.ts (base64 PNG data URIs, the poiPinImages.ts pattern) so the phone's gl-hazards
SymbolLayer and CarPlay / Android Auto's HazardMarker draw the same pixels.
  python3 tools/poi-pins/bake_hazards.py
"""
import base64, io, os, subprocess, sys, tempfile
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bake, emit_ts
from PIL import Image
sys.path.insert(0, os.path.join(bake.ROOT, "assets/carplay-glyphs/report"))
CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
KINDS = [("police", "ev", "police"), ("accident", "hospital", "crash"), ("road", "fastfood", "hazard"), ("traffic", "gas", "traffic")]
GLYPH_PT = 17          # the glyph's box on the 26 pt head
S = bake.S

def glyph_png(name, colour_hex, px):
    src = open(os.path.join(bake.ROOT, "assets/carplay-glyphs/report/gen_b.py")).read()
    ns = {}; exec(src.split("# bake sheet:")[0].replace("OUT = pathlib.Path(sys.argv[1])", "OUT = None"), ns)
    svg = ns["glyph"](name, colour_hex, None)
    html = (f'<!doctype html><html><head><meta charset="utf-8"><style>body{{margin:0;background:transparent;width:{px}px;height:{px}px;'
            f'display:flex;align-items:center;justify-content:center}}</style></head><body>'
            f'<svg viewBox="0 0 64 64" width="{px}" height="{px}" xmlns="http://www.w3.org/2000/svg">{svg}</svg></body></html>')
    with tempfile.TemporaryDirectory() as d:
        h = os.path.join(d, "g.html"); open(h, "w").write(html); out = os.path.join(d, "g.png")
        subprocess.run([CHROME, "--headless=new", "--disable-gpu", "--hide-scrollbars", "--force-device-scale-factor=1",
                        "--default-background-color=00000000", f"--window-size={px},{px}", f"--screenshot={out}", f"file://{h}"],
                       check=True, capture_output=True)
        return Image.open(out).convert("RGBA")

def hazard_pin(kind, cat, glyph):
    canvas, (CW, CH, ox, oy) = bake.bake_pin(bake.DEEP[cat], "")
    g = glyph_png(glyph, bake.BRIGHT[cat], GLYPH_PT * S * 4).resize((GLYPH_PT * S, GLYPH_PT * S), Image.LANCZOS)
    cx, cy = round(ox * S), round((oy + bake.HEAD_CY) * S)
    canvas.alpha_composite(g, (cx - g.width // 2, cy - g.height // 2))
    x0, x1 = round((ox - bake.PIN_W / 2 - emit_ts.MARGIN) * S), round((ox + bake.PIN_W / 2 + emit_ts.MARGIN) * S)
    y0, y1 = round((oy - bake.PIN_H - emit_ts.MARGIN) * S), round(oy * S)
    im = canvas.crop((x0, y0, x1, y1)); assert im.size == (emit_ts.W * S, emit_ts.H * S), im.size
    return im

def main():
    lines = [
        "// hazardPinImages.ts — GENERATED by tools/poi-pins/bake_hazards.py. Do not hand-edit; change the bake and re-run.",
        "// The crew-report pins (Jeff, 2026-09-25): the search-category teardrop in the category's DEEP shade with the Report",
        "// panel's Apple-symbol glyph in the BRIGHT shade on the head — Police = EV charging, Crash = Hospital, Hazard = Fast",
        "// Food, Traffic = Gas (src/hazardPalette.ts). Same box as poiPinImages.ts (POI_PIN_W × POI_PIN_H pt at POI_PIN_SCALE),",
        "// so the gl-hazards SymbolLayer draws them with iconSize 1/POI_PIN_SCALE and HazardMarker at POI_PIN_W × POI_PIN_H.",
        "export const HAZARD_PIN_B64: Record<string, string> = {",
    ]
    total = 0
    for kind, cat, glyph in KINDS:
        im = hazard_pin(kind, cat, glyph); s = emit_ts.b64(im); total += len(s)
        lines.append(f'  {kind}: "{s}",')
        im.save(os.path.join(os.path.dirname(os.path.abspath(__file__)), f"preview-hazard-{kind}.png"))
    lines += [
        "};",
        "export function hazardPinUri(kind: string): string { return \"data:image/png;base64,\" + (HAZARD_PIN_B64[kind] ?? HAZARD_PIN_B64.road); }",
        "/** name → { uri } for <Images images={…}> on the phone map: hz_pin_<kind>. */",
        "export const HAZARD_PIN_IMAGES: Record<string, { uri: string }> = Object.fromEntries(",
        "  Object.keys(HAZARD_PIN_B64).map((k) => [\"hz_pin_\" + k, { uri: \"data:image/png;base64,\" + HAZARD_PIN_B64[k] }]),",
        ");",
    ]
    out = os.path.join(bake.ROOT, "src/hazardPinImages.ts"); open(out, "w").write("\n".join(lines) + "\n")
    print(f"wrote {out}: {len(KINDS)} pins, base64 total {total/1024:.0f} KB")

if __name__ == "__main__":
    main()
