#!/usr/bin/env python3
"""emit_ts.py — bake the app's search-category pins into src/poiPinImages.ts (base64 PNG data URIs).

Run: python3 tools/poi-pins/emit_ts.py        (after any change to bake.py — bake.py is the design source)

Why data URIs: the bytes ride the JS bundle (OTA-able, no asset path-key trap) and the phone's gl-places
SymbolLayer, CarPlay/AA's PlaceMarker (RN Image) all draw the SAME pixels — the wxCalloutImages.ts pattern.
The pin is baked WITHOUT its number (bake_pin(hex, "") draws no digit): the app draws the result number
live, so any count works. Cropped so the teardrop's TIP is exactly on the bottom edge (Mapbox iconAnchor
"bottom" / MarkerView anchor y=1 put the tip on the coordinate) with MARGIN pt kept around the sides and
top for the shadow/highlight. One entry per category x deep/bright, plus "neutral" (src/poiPalette.ts
POI_NEUTRAL) for a result that carries no category.
"""
import os, sys, io, base64
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import bake  # noqa: E402  — tools/poi-pins/bake.py: geometry (PIN_W/H, HEAD_R, HEAD_CY), palette (BRIGHT/DEEP), bake_pin
from PIL import Image  # noqa: E402

S = bake.S
MARGIN = 3
NEUTRAL = {"deep": "#2B3340", "bright": "#9BA8B8"}   # keep in step with src/poiPalette.ts POI_NEUTRAL
W, H = bake.PIN_W + 2 * MARGIN, bake.PIN_H + MARGIN   # points
NUM_PT = 15                                            # bake_pin's digit size — the app's live number matches it


def app_pin(fill_hex):
    canvas, (CW, CH, ox, oy) = bake.bake_pin(fill_hex, "")
    x0, x1 = round((ox - bake.PIN_W / 2 - MARGIN) * S), round((ox + bake.PIN_W / 2 + MARGIN) * S)
    y0, y1 = round((oy - bake.PIN_H - MARGIN) * S), round(oy * S)
    im = canvas.crop((x0, y0, x1, y1))
    assert im.size == (W * S, H * S), im.size
    return im


def b64(im):
    buf = io.BytesIO(); im.save(buf, "PNG", optimize=True); return base64.b64encode(buf.getvalue()).decode()


def main():
    keys = list(bake.BRIGHT.keys()) + ["neutral"]
    lines = [
        "// poiPinImages.ts — GENERATED by tools/poi-pins/emit_ts.py from tools/poi-pins/bake.py. Do not hand-edit;",
        "// change the bake and re-run. Search-category map pins (Jeff, 2026-09-23, off a Mapbox screenshot): a small",
        "// SOLID teardrop in the category's deep colour (bright = the cheapest gas station), no glyph, no ring; the",
        "// result number is drawn LIVE by the app in white on the head. Data URIs so the phone's gl-places",
        "// SymbolLayer and CarPlay/AA's PlaceMarker draw the same pixels (the wxCalloutImages.ts pattern).",
        f"export const POI_PIN_W = {W};            // points; the tip is on the bottom edge, centred",
        f"export const POI_PIN_H = {H};",
        f"export const POI_PIN_SCALE = {S};        // px per point in the PNGs (iconSize 1/POI_PIN_SCALE draws them at point size)",
        f"export const POI_PIN_HEAD_R = {bake.HEAD_R};        // head circle radius, points",
        f"export const POI_PIN_HEAD_ABOVE_TIP = {-bake.HEAD_CY};   // head centre above the tip, points — where the number goes",
        f"export const POI_PIN_NUM_PT = {NUM_PT};       // the number's size (bold, white)",
        'export type PoiPinVariant = "deep" | "bright";',
        "export const POI_PIN_B64: Record<string, string> = {",
    ]
    total = 0
    for k in keys:
        pal = NEUTRAL if k == "neutral" else {"deep": bake.DEEP[k], "bright": bake.BRIGHT[k]}
        for v in ("deep", "bright"):
            s = b64(app_pin(pal[v])); total += len(s)
            lines.append(f'  "{k}/{v}": "{s}",')
    lines += [
        "};",
        "const KEY = (cat: string | undefined, variant: PoiPinVariant): string => (cat && (cat + \"/\" + variant) in POI_PIN_B64 ? cat : \"neutral\") + \"/\" + variant;",
        "/** The registered Mapbox image name for a pin: poi_<cat>_<variant> (POI_PIN_IMAGES holds every one). */",
        "export function poiPinImageName(cat: string | undefined, variant: PoiPinVariant): string { return \"poi_\" + KEY(cat, variant).replace(\"/\", \"_\"); }",
        "export function poiPinUri(cat: string | undefined, variant: PoiPinVariant): string { return \"data:image/png;base64,\" + POI_PIN_B64[KEY(cat, variant)]; }",
        "/** name → { uri } for <Images images={…}> on the phone map. */",
        "export const POI_PIN_IMAGES: Record<string, { uri: string }> = Object.fromEntries(",
        "  Object.keys(POI_PIN_B64).map((k) => [\"poi_\" + k.replace(\"/\", \"_\"), { uri: \"data:image/png;base64,\" + POI_PIN_B64[k] }]),",
        ");",
    ]
    out = os.path.join(bake.ROOT, "src/poiPinImages.ts")
    open(out, "w").write("\n".join(lines) + "\n")
    print(f"wrote {out}: {len(keys)*2} pins, {W}x{H} pt @{S}x, base64 total {total/1024:.0f} KB")


if __name__ == "__main__":
    main()
